---
- name: Check if resolvectl command exists
  ansible.builtin.command: which resolvectl
  register: resolvectl_check
  ignore_errors: true
  changed_when: false
  no_log: "{{ general_hide_dns_logs }}"

- name: Configure systemd-resolved via template
  become: true
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  when: resolvectl_check.rc == 0
  notify: Restart systemd-resolved
  no_log: "{{ general_hide_dns_logs }}"

- name: Configure resolv.conf directly
  become: true
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
    force: true
  when:
    - resolvectl_check.rc != 0
    - not (general_ignore_dns_resolv_task | default(false) | bool)
  no_log: "{{ general_hide_dns_logs }}"
